### ISSUE TITLE
WiFi ipx connector 

### ISSUE THREAD

**Issue by dodo124** [Xinyuan-LilyGO/LilyGo-LoRa-Series#102]
Hi, which resistor has to be removed when using the ipx connector? I can't find the information.

Thanks Dominik

**Comment by balynt2048** [comment]
Well first please specify which board you have.

**Comment by dodo124** [comment]
Oh my bad. Sorry. I do have the following board: GO®
LoRa32 V2.1_1.6. Regards Dominik

**Comment by balynt2048** [comment]
Are you sure it is this https://www.aliexpress.com/i/32872078587.html ? What does it say on the board? I don't see a second ipex connector for the wifi, only one for the LoRa antenna.
If you look at for example the T3S3 v1.1 board (which I have right now), there are two ipex connectors.

**Comment by dodo124** [comment]
Hi,
Yes it's the board and it only has one ipx like it is shown in the picture. So I guess there is no way to attach a ipx to the board. The problem is that the onboard WLAN antenna has fallen off. So I can't turn on WiFi. Any suggestions in my particular case?

Regards Dominik 

Am 21. September 2023 11:18:23 MESZ schrieb PBalint ***@***.***>:
