### ISSUE TITLE
Lilygo TTGO V2.1 Battery DIO Pin Number

### ISSUE THREAD

**Issue by Edgineer10** [Xinyuan-LilyGO/LilyGo-LoRa-Series#105]
I would like to monitor the Battery Level of my Lilygo TTGO V2.1. What pin should I use?

**Comment by lewisxhe** [comment]
Which board is V2.1? Here is the schematic link. I don’t know which one you are talking about. If it is the ESP32 version, most IO measurements use IO35.
https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/tree/master/schematic
