### ISSUE TITLE
SSD1309 support

### ISSUE THREAD

**Issue by freiregtr** [Xinyuan-LilyGO/LilyGo-LoRa-Series#108]
Hello, I would like to know if there is support for the OLED based on the SSD1309, since I have tested the SSD1306 OLEDs and they work well, they even work as a master-slave, but when I disconnect the SSD1306 OLED, the SSD1309 does not work.

**Comment by lewisxhe** [comment]
Of course it supports SSD1309. I remember using the U8G2 library, which supports SSD1309. I can't test it for you because I don't have this screen.
