### ISSUE TITLE
Missing component PN in T-Beam v1.1 schematic

### ISSUE THREAD

**Issue by fanoway** [Xinyuan-LilyGO/LilyGo-LoRa-Series#110]
The following chips/components are given a designation in the schematic for the V1.1 t-beam but there is no documentation to sate what the PN is of the part. A whole BOM would be preferable

- U22 - TTGO LORA
    - Presumably this is SX module?
- U54
- ANT3
- U15
- U1

There may be others, but this is my list so far

**Comment by lewisxhe** [comment]
U22 sx126x module
U54 SMA ANT
ANT3 = IPEX1
U1 = 40MHZ crystal oscillator

**Comment by lewisxhe** [comment]
After a long period of inactivity, the question will be closed.
