### ISSUE TITLE
serial monitor not printed and SD card FAILED error

### ISSUE THREAD

**Issue by cchantra** [Xinyuan-LilyGO/LilyGo-LoRa-Series#112]
I got T BEAMS Supremes ESP32S3.
I ran the example QM8658 GetData but I go the error SDCard FAILED on screen and 
the serial monitor not showing anything.
Please help me.

Regards
chantana

**Comment by lewisxhe** [comment]
Sorry, I have fixed it, please try again

**Comment by cchantra** [comment]
Thanks, it works now.
