### ISSUE TITLE
Unable to Download the library 

### ISSUE THREAD

**Issue by vemanthchandrap** [Xinyuan-LilyGO/LilyGo-LoRa-Series#114]
Hey, I am getting error while downloading the LilyGo-LoRa-Series library in Arduino IDE.

**Comment by lewisxhe** [comment]
What is wrong ? Please take a screenshot of the error message

**Comment by vemanthchandrap** [comment]
Hey the issue is sorted. Thank you

**Comment by lewisxhe** [comment]
Then I will close the issue
