### ISSUE TITLE
Lmic library not supporting SX1262 radio

### ISSUE THREAD

**Issue by rodri16** [Xinyuan-LilyGO/LilyGo-LoRa-Series#116]
Hi, have you tested SX1262 radio with Arduino LMIC? I am interested in TTGO LORA32S3 v1.2. Thanks

**Comment by lewisxhe** [comment]
LMIC does not originally support SX1262. RadioLib already contains LoRaWAN examples, you can check it out.

**Comment by rodri16** [comment]
Thanks @lewisxhe,
I cannot find examples you say.
LilyGo-LoRa-Series/lib/RadioLib/examples/SX126x no LoRaWAN examples

**Comment by lewisxhe** [comment]
I am referring to the upstream RadioLib. After you are familiar with using local examples, you can switch to the mainline branch for development.

https://github.com/jgromes/RadioLib/tree/master/examples/LoRaWAN

**Comment by rodri16** [comment]
So in Radiolib dev branch I could change radio to SX1262 and make example work? Will test it...
examples/LoRaWAN/LoRaWAN_End_Device_APB
SX1262 lora = new Module(NSS,DIO1,NRST,BUSY);
