### ISSUE TITLE
SX1280 Ranging Issue: Incorrect Distance Readings on Master and Slave Boards

### ISSUE THREAD

**Issue by Eden-Sheiko** [Xinyuan-LilyGO/LilyGo-LoRa-Series#118]
Description:
I am currently working on a ranging project using two LilyGo LoRa boards equipped with the SX1280 module. In my setup, one board functions as the master and the other as the slave. Despite correct configuration, I am facing a significant issue: the slave board consistently reports a distance of 0, while the master board registers an implausibly vast distance of 370,096.28 km. This discrepancy is hindering the project's progress, as I need accurate distance measurements for the application to work effectively.

Setup Details:

Hardware: Two units of LoRa SX1280 T3 1.8V
Steps to Reproduce:

Programmed the master board with the 'SX128x_RangingMaster' sketch from examples/RadioLibExamples/SX1280/Ranging.
Loaded the 'SX128x_RangingSlave' sketch onto the slave board from the same directory.
Expected Behavior:
The expectation was for both boards to display realistic and accurate distance measurements, reflecting the actual physical distance between them.

Actual Behavior:
Contrary to expectations, the slave board persistently shows a distance reading of 0, while the master board indicates an unrealistically high distance of 370,096.28 km.

Tags: bug, help wanted, SX1280, ranging

**Comment by lewisxhe** [comment]
You can check this issue here, I can't do anything at all
https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/issues/91
