### ISSUE TITLE
LoRa32 V2.1_1.6 with PaxCounter green led is blink fast, why?

### ISSUE THREAD

**Issue by cc13com** [Xinyuan-LilyGO/LilyGo-LoRa-Series#120]
Hello,

I bought the LoRa32 V2.1_1.6, created credentials for "The Things Network", added this creadentials to the PaxCounter sketch and have uploaded that on the board.

The display is showing a few WLAN clients and other information. But the Board will not send any information to TTN. Ok, it could be that there is no gateway next to me.

However, I am more surprised about the fast blinking green led. I did not find any information in the documentation for that. On the other hand I have seen an article wrote about this blinking and mentioned that the board has a hardware defect if the green led is blinking fast.

Any idea what that fast green blinking means?

**Comment by lewisxhe** [comment]
I haven't used Paxcounter, I think I found part of the explanation in the Paxcounter source code, I think you should go to Paxcounter and ask Verkehrsrot

![image](https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/assets/22990954/d097083e-1946-4233-a5d1-2867933463fc)

**Comment by cyberman54** [comment]
Quick blinking LED on paxcounter board means, the device has not yet joined into a LORAWAN network.
Either there is no radio coverage (no LORAWAN gateway in range), or the network credentials are missing und unmatching.
