### ISSUE TITLE
It does not install, ERROR 13: Library install failed: moving extracted archive to destination dir: Library not valid. Most recent version of IDE

### ISSUE THREAD

**Issue by BlueSkySunset76** [Xinyuan-LilyGO/LilyGo-LoRa-Series#123]

**Comment by lewisxhe** [comment]
How do you move?

**Comment by Zanctarios** [comment]
I am having the exact same problem! I tried using the .zip file downloading these files: https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/tree/master
And I click the Add Zip Library, under the **Sketch-> Include Library -> Add Zip Library option.**
Am I doing something wrong here?

Thanks in advance!

**Comment by lewisxhe** [comment]
@Zanctarios This repository is not a library, just examples and resources
How to use please see the home page README

**Comment by BlueSkySunset76** [comment]
That’s the correct procedure but it doesn’t work. I haven’t found the right way yet but I will and I’ll let you know as soon as I have it. Meanwhile they work well with other libraries and I’ve found them to be reliable.D:On Jan 7, 2024, at 4:06 PM, Zanctarios ***@***.***> wrote:﻿
I am having the exact same problem! I tried using the .zip file downloading these files: https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/tree/master
And I click the Add Zip Library, under the Sketch-> Include Library -> Add Zip Library option.
Am I doing something wrong here?
Thanks in advance!
