### ISSUE TITLE
switch resistor for external WiFi Antenna T3_V1.6.1

### ISSUE THREAD

**Issue by maho24at** [Xinyuan-LilyGO/LilyGo-LoRa-Series#124]
Hi guys, 

which resistors do I have to change in case I want to use the ipx connector for WiFi? 

Board: T3_V1.6.1

thank you!!

![WIN_20231217_19_52_00_Pro](https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/assets/100833349/1a68b4ad-7b6b-4caf-8d71-999a52dc9d6b)

![WIN_20231217_19_52_29_Pro](https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/assets/100833349/3d0f3327-bb91-48b3-98ce-a0248973f101)

**Comment by lucaleicht** [comment]
I have the same question. But actually after a little research i think the ipex con we can find in yout second picture is just the second socket für the lora antenna (433/868/... MHz). If not, I'd be very interested too!

**Comment by maho24at** [comment]
I also did some measurements, and looked at the tracing, I guess its just a false information on the website - maybe lost in translation... unfortunately...

**Comment by lewisxhe** [comment]
![image](https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/assets/22990954/c2d92545-6b3d-41a7-b896-06ac296934d7)
Rotate 90° to the right
