### ISSUE TITLE
LoRa V1.0 ESP32 SX1276 (868/915Mhz)

### ISSUE THREAD

**Issue by wolfgangmauer** [Xinyuan-LilyGO/LilyGo-LoRa-Series#126]
I got some of [these](https://de.aliexpress.com/item/32845370112.html) boards.
In the original flashed sketch, the blue LED flashes 1Hz.
But I can't find any(old) example source that does exactly that.
How to access the charging unit?

#define LILYGO_T3_V1_0

> LoRa Sender
> Sending packet: 0
> Sending packet: 1
> Sending packet: 2
> Sending packet: 3
> Sending packet: 4
> Sending packet: 5
> Sending packet: 6

Please guide me to the correct sample source!!!

THX

**Comment by lewisxhe** [comment]
https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/tree/master/examples%2FArduinoLoRa

**Comment by wolfgangmauer** [comment]
THX!
The blue LED is at what Pin?
How to access the charging unit, if possible(detect charging)?

**Comment by lewisxhe** [comment]
1. Charging instructions
2. Unable to detect
