### ISSUE TITLE
T3S3v1.2 sx1280 PA RadioLibExample not working

### ISSUE THREAD

**Issue by 53-74-65-66-61-6e** [Xinyuan-LilyGO/LilyGo-LoRa-Series#131]
Hello,

can someone confirm, that the Lilygo T3S3 v1.2 SX1280 PA board works out of the box with the provided example ( [https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/tree/master/examples/RadioLibExamples/SX1280](https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/tree/master/examples/RadioLibExamples/SX1280) ) ?

I am able to compile and upload the tx and rx example programs in vscode+platformio and the displays are working, but no data is received. I did some research in the RadioLib documentation, but no success so far.

To verify, that my boards are not broken, i can flash meshtastic and that defintiely works.

One thing, which does not seem to comply with RadioLib is the initalization of SPI. According to RadioLib, the SPI Class should be handed over in radio.begin() like here: [https://github.com/jgromes/RadioLib/wiki/Basics#non-standard-spi-setup](https://github.com/jgromes/RadioLib/wiki/Basics#non-standard-spi-setup)
I tried that as well, but still no luck.

Before i dive into more details, it would be helpful to know, if others are having success with this example on these boards.

best regards, Stefan

**Comment by lewisxhe** [comment]
Please paste your test code

**Comment by 53-74-65-66-61-6e** [comment]
My test code is the example from Lilygo Github:
[examples/RadioLibExamples/SX1280](url)

**Comment by 53-74-65-66-61-6e** [comment]
i tried again step by step:
- download /LilyGo-LoRa-Series-master/
- open with platformio in vscode
- in platformio.ini uncomment: default_envs = T3_S3_V1_1_SX1280

1. in platformio.ini uncomment:
`src_dir = examples/RadioLibExamples/SX1280/SX128x_Transmit_Interrupt`
- compilation and upload works. board boots and displays "Transmitting: OK!"

3. in platformio.ini uncomment:
`src_dir = examples/RadioLibExamples/SX1280/SX128x_Receive_Interrupt`
- compilation fails with errors:
`In file included from /LilyGo-LoRa-Series-master/examples/RadioLibExamples/SX1280/SX128x_Receive_Interrupt/SX128x_Receive_Interrupt.ino:28:
examples/RadioLibExamples/SX1280/SX128x_Receive_Interrupt/boards.h:116:15: error: redefinition of 'SPIClass SDSPI'
 SPIClass SDSPI(HSPI);

/LilyGo-LoRa-Series-master/examples/RadioLibExamples/SX1280/SX128x_Receive_Interrupt/SX128x_Receive_Interrupt.ino: In function 'void loop()':
/LilyGo-LoRa-Series-master/examples/RadioLibExamples/SX1280/SX128x_Receive_Interrupt/SX128x_Receive_Interrupt.ino:199:53: error: 'str' was not declared in this scope
                 snprintf(buf, sizeof(buf), "RX:%s", str);`

**Comment by puboy7** [comment]
Please use the latest uploaded code. The specific problem is to accommodate the use of new screens and new versions of edp screens but to repeatedly define SDSPI at design time. Sorry for the inconvenience

**Comment by 53-74-65-66-61-6e** [comment]
Great, it works! ![photo](https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/assets/157323054/caa1e6b2-f9ef-4691-85c9-c17245394928)

Thank you very much for the direct support.

**Comment by puboy7** [comment]
It's my pleasure.

**Comment by 53-74-65-66-61-6e** [comment]
one more thing. It would be nice, if the example shows the text which was send by the transmitter.

In [SX128x_Receive_Interrupt.ino](https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/blob/master/examples/RadioLibExamples/SX1280/SX128x_Receive_Interrupt/SX128x_Receive_Interrupt.ino) use arduino string instead of counter:
```
// you can read received data as an Arduino String
String str;
int state = radio.readData(str);
/*
uint32_t counter;
int state = radio.readData((uint8_t *)&counter, 4);
*/
```
here at Serial print:
```
// print data of the packet
Serial.print(F("[SX1280] Data:\t\t"));
//Serial.println(counter);
Serial.println(str);
```
and here at oled output:
```
//snprintf(buf, sizeof(buf), "Data:%s", counter);
str = "Data: " + str;
str.toCharArray(buf, 256);
u8g2->drawStr(0, 26, buf);
```

**Comment by 53-74-65-66-61-6e** [comment]
![Hello World](https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/assets/157323054/c3af1d8c-0d8e-40bb-8d98-01922c5302b6)

**Comment by puboy7** [comment]
Yes, as you can see in the sample code for other models there are also examples that show you what you want according to your requirements

**Comment by puboy7** [comment]
Our original plan was to remove the use of pa mode in version 1.2 but later added it back so please try it with the latest code

**Comment by 53-74-65-66-61-6e** [comment]
I was confused, because in the schematics, there is no lora_tx and lora_rx at U1 HDP17.

Are these pins unique to the PA versions of the chips?

**Comment by puboy7** [comment]
The PA version does not have lora_tx and lora_rx so you need to define it by yourself
