### ISSUE TITLE
CANNOT Reset with firmware/NMEA_Reset/TBEAM_V1X_NMEA_RESET.bin

### ISSUE THREAD

**Issue by m2mlorawan** [Xinyuan-LilyGO/LilyGo-LoRa-Series#134]
I have Tbeam T22_V1.1 20210222 Ublox NEO6M

My Tbeam not send out NMEA protocal.

I did as in https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/blob/master/firmware/NMEA_Reset/README.MD

Not help.
```
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13192
load:0x40080400,len:3028
entry 0x400805e4
initBoard
Warning: Failed to find AXP2101 power management
AXP192 PMU init succeeded, using AXP192 PMU
=========================================
DC1  : +   Voltage: 3300 mV 
DC2  : -   Voltage: 1800 mV 
DC3  : +   Voltage: 3300 mV 
LDO2 : +   Voltage: 3300 mV 
LDO3 : +   Voltage: 3300 mV 
=========================================
PowerKeyPressOffTime:4 Second
Started OLED
recovery failed!

```

**Comment by m2mlorawan** [comment]
Using this, do not help.
https://github.com/eriktheV-king/TTGO_T-beam_GPS-reset/blob/master/T22-GPS-reset-v3/T22-GPS-reset-v3.ino

Stop at  All comms started.

ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1184
load:0x40078000,len:13260
load:0x40080400,len:3028
entry 0x400805e4
Connected to Serial
AXP192 Begin PASS
All comms started

**Comment by lewisxhe** [comment]
![image](https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/assets/22990954/06758a17-b375-4c68-a87e-b7de08acb789)
If nothing is output, then you need to check whether the GPS power supply is normal.

What firmware did you use that caused this? I can test it, but please make sure the power supply is normal first

**Comment by m2mlorawan** [comment]
I checked power supply is 3.19V.  Firmware is TBEAM_V1X_NMEA_RESET.bin

**Comment by lewisxhe** [comment]
It is unlikely that all three are damaged. It may be that the wrong firmware was written, causing the baud rate to change and unable to communicate with the GPS. Can you tell me what firmware you wrote before? I can investigate

**Comment by m2mlorawan** [comment]
I think baud rate is OK.
My MicroPython script can read serial port as speed 9600bps.
It display data like this.

b'\xc3\x19\x18\x18\xfa\xc3\x19\x18\x18\xfa'
b'\xc3\x19\x18\x18\xfa\xc3\x19\x18\x18\xfa\xc3\x19\x18\x18\xfa\xc3\x19\x18\x18\xfa\xc3\x19\x18\x18\xfa\xc3\x19\x18\x18\xfa'
b'\xc3\x19\x18\x18\xfa\xc3\x19\x18\x18\xfa\xc3\x19\x18\x18\xfa\xc3\x19\x18\x18\xfa\xc3\x19\x18\x18\xfa\xc3\x19\x18\x18\xfa'
b'\xc3\x19\x18\x18\xfa\xc3\x19\x18\x18\xfa\xc3\x19\x18\x18\xfa\xc3\x19\x18\x18\xfa\xc3\x19\x18\x18\xfa\xc3\x19\x18\x18\xfa'

It is not NEMEA Protocol.

This is my MicroPython Script.

from machine import UART
from time import sleep
uart1 = UART(1, 9600)  
uart1.init(9600, bits=8, parity=None, stop=1, tx=12, rx=34)
sleep(1)
while True:
    print(uart1.read())
    sleep(2)

**Comment by lewisxhe** [comment]
The bytecode you provided cannot be decoded into a valid string. I feel that you have set the wrong baud rate, causing the received string to be incorrect. If the GPS continues to output messages, then it is certain that the GPS is working. Can you try other baud rates?

If you can find a sketch you ran previously, look for other information such as the set baud rate from the previous sketch.

**Comment by m2mlorawan** [comment]
Thank lewisxhe, 
           Your guess is right. I change GPS baud rate to 115200. It is now working.
This happen because I installed https://github.com/Max-Plastix/tbeam-helium-mapper.
I open https://github.com/Max-Plastix/tbeam-helium-mapper/blob/main/main/configuration.h and found  on line 193 

#define GPS_BAUDRATE 115200  // Make haste!  NMEA is big.. go fast 

This should be the cause. I used a Reset Baud Rate program from GITHUB to reset it back to 9600bps.

Thank you.

**Comment by lewisxhe** [comment]
Okay, thank you for trying. It seems that I can further improve NMEA_Reset.
