### ISSUE TITLE
T beam supreme bricked?

### ISSUE THREAD

**Issue by preshantram** [Xinyuan-LilyGO/LilyGo-LoRa-Series#137]
Hi, I've uploaded a firmware with the JTAG debug on,
Now I cannot upload a firmware anymore, previously I could press the boot button shortly after reset which allowed me to upload a new firmware, but I cannot put my T beam Supreme in this option anymore, boot button doesn't seem to do a thing.

Any ideas??

**Comment by lewisxhe** [comment]
![image](https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/assets/22990954/0533d25a-5d65-4408-8187-e058b437f277)

1. Connect the board via the USB cable
2. Press and hold the BOOT button , While still pressing the BOOT button, press RST
3. Release the RST
4. Release the BOOT button
5. Upload sketch

**Comment by lyusupov** [comment]
> previously I could press the boot button shortly after reset which allowed me to upload a new firmware, but I cannot put my T beam Supreme in this option anymore

https://github.com/adafruit/tinyuf2/tree/master/ports/espressif
