### ISSUE TITLE
Lily Go Lora with Arduino specifically the board t-higrow lora32 868MHz

### ISSUE THREAD

**Issue by hoceyne** [Xinyuan-LilyGO/LilyGo-LoRa-Series#138]
Hello, 
I want how to apply this example **[Arduino examples](https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/tree/master/examples/ArduinoLoRa)** on the following board
![fdjskf](https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/assets/39886431/05322d54-6646-45d4-96f8-01276ece73a0)
and my problem I don't know how to connect those pins to arduino uno

**Comment by lewisxhe** [comment]
@hoceyne 

![image](https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/assets/22990954/aba98b99-1eb7-485e-b9c8-35e71effcc34)
