### ISSUE TITLE
Unable to find correct 'Board' for SX1280 PA T3S3 V1.2

### ISSUE THREAD

**Issue by sirfonzie** [Xinyuan-LilyGO/LilyGo-LoRa-Series#143]
I am unable to find any working 'board' under the Arduino IDE. I have tried Arduino version 1.8.x and 2.x.
I cant even find the following in my listing even though the readme stated that it should be there: "T3-S3-V1.0".

I am using the following board (SX1280 2.4G With PA [H658]):
https://www.lilygo.cc/products/t3s3-v1-0?variant=43043715678389

Please advise.

**Comment by lewisxhe** [comment]
Chose  ESP32 S3 DEV MODULE
https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series#3%EF%B8%8F%E2%83%A3arduino-ide-quick-start
