### ISSUE TITLE
Powering options

### ISSUE THREAD

**Issue by nicklasb** [Xinyuan-LilyGO/LilyGo-LoRa-Series#147]
Hi!

I cannot find somewhere authoritative where the different power options for the T-Beam v1.1 are described. 

That it can be powered using USB is obvious, but it is not clear if the battery is charged if power is provided through the 5v pin, for example, "someone on the internet" think that it won't be charged then, which would narrow the possible usages of the board.
Power using USB is certainly not always an option, at least not in my use case.

**Comment by lewisxhe** [comment]
Cannot be charged via 5V Pin.

**Comment by nicklasb** [comment]
> Cannot be charged via 5V Pin.

Does that mean that the only way to charge it is using the USB? 
Is there no other way but adding an external charge controller?

**Comment by lewisxhe** [comment]
When T-Beam v1.1 was first designed, there was no external power supply input interface reserved other than USB. If you don’t want to connect the power supply from USB, you can connect the power supply from the arrow in the picture below. This is the same as the USB input. A line, plugged in here, means USB power is enabled.

![image](https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/assets/22990954/b4b7edab-4340-4273-998b-9af056945e95)

**Comment by StijnVerhelst** [comment]
> When T-Beam v1.1 was first designed, there was no external power supply input interface reserved other than USB. If you don’t want to connect the power supply from USB, you can connect the power supply from the arrow in the picture below. This is the same as the USB input. A line, plugged in here, means USB power is enabled.
> 
> ![image](https://private-user-images.githubusercontent.com/22990954/316694668-b4b7edab-4340-4273-998b-9af056945e95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NjIzNjEsIm5iZiI6MTcxMTQ2MjA2MSwicGF0aCI6Ii8yMjk5MDk1NC8zMTY2OTQ2NjgtYjRiN2VkYWItNDM0MC00MjczLTk5OGItOWFmMDU2OTQ1ZTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDE0MDc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiODcwNDM1ZTIyMTJiN2U2YWEyMDg4MjdjNmJiZDJlMzk4ODUxYjFmNzNiNzc5NjU1ODI0YjIzZmZmN2ViNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uzFp6WuQ_z7OUAoNE0zo9CizZwqQ_MK7WMl_H7q4WqQ)

I have a similar use-case, are we allowed to connect the 5V pin to the capacitor?

**Comment by lewisxhe** [comment]
Of course, please remember that the location of this capacitor is the location of the USB 5V input.

**Comment by nicklasb** [comment]
> When T-Beam v1.1 was first designed, there was no external power supply input interface reserved other than USB.

Does this indicate that there are less hacky methods for the 1.2?
