### ISSUE TITLE
Lily Go T-Beam Supreme connected wtih GSM GPRS 

### ISSUE THREAD

**Issue by cchantra** [Xinyuan-LilyGO/LilyGo-LoRa-Series#152]
Is it possible to connect Lily GO T-BEAM Supreme with  GPS GPRS  such as SIM900A ?
Can you suggest?

Regards
chantana

**Comment by lewisxhe** [comment]
Of course, any free IO port can serve as Serial.
Example
```
     Serial2.begin(GPS_BAUD_RATE, SERIAL_8N1, RX_PIN, TX_PIN);
```

**Comment by cchantra** [comment]
Hello,

After I put the pins on the board, my board is not working like before.
USB doesn't work anymore. After I pushed reset and plug in the usb again.
The board type before TAMC Termod S3 as in the screen below.

How to fix this? Should I reflash the firmware?

Thank you.



ในวันที่ พ. 10 เม.ย. 2024 เวลา 09:03 Lewis He ***@***.***>
เขียนว่า:

**Comment by cchantra** [comment]
Hi
I cannot flash the firmware. The error says
Could not open /dev/cu.usbmodem1201, the port is busy or doesn't exist.

When I pressed boot and reset, the port appears but there is such error
when I tried to flash, then the port disappeared.

How to fix this?

Regards
chantana

ในวันที่ ส. 13 เม.ย. 2024 เวลา 18:13 chantana chantrapornchai <
***@***.***> เขียนว่า:

**Comment by lewisxhe** [comment]
https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/issues/137

**Comment by cchantra** [comment]
hello, we need to flash bootloader again with linux?

regards


ในวันที่ จ. 15 เม.ย. 2024 เวลา 08:05 Lewis He ***@***.***>
เขียนว่า:

**Comment by cchantra** [comment]
hello, I tried to use binary from the website to flash the board. (tbeam-s3)
https://github.com/adafruit/tinyuf2/releases
but after I flashed, arduino detected the board as
 Lolin c3 mini after awhile the connected port is disconnected.

I cannot upload the program.
Is the board broken?

chantana

ในวันที่ ศ. 19 เม.ย. 2024 เวลา 21:34 chantana chantrapornchai <
***@***.***> เขียนว่า:

**Comment by lewisxhe** [comment]
![image](https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/assets/22990954/fc308449-b661-4c86-b6f4-3cc332cf04ea)
If you write the wrong firmware, it will reboot indefinitely and you must enter download mode manually.
