### ISSUE TITLE
Reconfigure 868z T-BeamSUPREME for 915 MHz

### ISSUE THREAD

**Issue by cwg523** [Xinyuan-LilyGO/LilyGo-LoRa-Series#154]
Can I reconfigure a 868MHz T-BeamSUPREME for 915 MHz?
It seems the sx1262 supports 868MHz  or 915MHz, so can I just flash the firmware (or change a constant) to change between frequencies? Is the otherwise hardware frequency agnostic?

**Comment by lewisxhe** [comment]
If you purchase the 868 version, you can directly change the frequency to 915, but the optimal signal frequency of the default antenna is 868. If you change it to 915, you can also use it, but the signal is not the best.
