### ISSUE TITLE
SMD component getting really hot during charging T3-S3 V1.2

### ISSUE THREAD

**Issue by Vincent-NB** [Xinyuan-LilyGO/LilyGo-LoRa-Series#159]
https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/assets/104589489/99293511-a4d7-4280-902b-2e51358cc181

Board: V1.2 T3-S3 2.4gHz Lora with PA
This SMD component is getting really hot whilst charging, up to 95°C within seconds.
I don't want to risk loosing this board so I haven't tried much longer.
Is this within the acceptable temperature range?

**Comment by lewisxhe** [comment]
Can you tell me what battery you are using, what its voltage is, and what its capacity is?
