### ISSUE TITLE
Trouble Receiving Signal with Lilygo LoRa32 433 v2.1 for Garage Door Opener

### ISSUE THREAD

**Issue by potabash** [Xinyuan-LilyGO/LilyGo-LoRa-Series#160]
**Issue Description:**
I recently purchased a Lilygo LoRa32 433 v2.1 (SX1278 LoRa module) with the intention of using it to open my garage door. However, I'm encountering difficulties in receiving the signal.

**Steps Taken:**
1. I attempted to use both SX1278_Receive.ino and SX1278_Receive_Interrupt.ino sketches provided, with the modification of listening at 433.92MHz (int state = radio.begin(433.92)).
2. Despite these attempts, the serial monitor remains empty, indicating that no signal is being received.
3. To troubleshoot further, I utilized SX1278_Transmit.ino to transmit a signal and then captured it using Flipper's "Read RAW" functionality.
4. I then attempted to replay this saved signal to my LoRa device using SX1278_Receive.ino, but still encountered the same issue of not receiving any signal.

**Request for Assistance:**
I am seeking advice on what might be causing this issue and how I can resolve it. Any insights or suggestions would be greatly appreciated.

**Additional Information:**
Model: Lilygo LoRa32 433 v2.1
Module: SX1278 LoRa
Frequency Used: 433.92MHz

**Comment by lewisxhe** [comment]
SX1278_Receive_Interrupt is only suitable for communication with LoRa modulation and demodulation. If your sending end does not belong to LoRa, but belongs to a modulation method such as FSK, the signal will not be received.
