### ISSUE TITLE
No examples of T3_V1.6.1 using display and SD card

### ISSUE THREAD

**Issue by jorgie0** [Xinyuan-LilyGO/LilyGo-LoRa-Series#162]
There are no examples of this T3_V1.6.1 using display and SD card.
Due to the complication of having to SPI devices connected an example using the Display and SD card should be created.

**Comment by lewisxhe** [comment]
https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/tree/master/examples/RadioLibExamples  Already included in the example
