### ISSUE TITLE
How to use MESHTASTIC with more personalised configuration?

### ISSUE THREAD

**Issue by dms-rj** [Xinyuan-LilyGO/LilyGo-LoRa-Series#167]
I will try in soon the CLI option to disbord the android and desktop meshtastic app limitation, that presents only the VeryLong_Slow, and others. That, VeryLong_Slow, is the reason that I opened this Ask, because it is the only option available in the meshtastic android app, in the CLI seems to be more options and I will try it, but not presents the 10.4KHz that I will speak at this text down in follow, and in the link https://meshtastic.org/docs/configuration/radio/lora/#lora-config-client-availability it's available only the 31KHz, less than it is not possible to set I guess, that will be tested in soon too.
1- I want to obtain the best config to get the most long range and don't matter to me how data per second is sent, I want long distance to send an information, such as GPS location, little packets of data (telemetry) and short messages, such as "I arrived and I am fine!" or "The mission runned very well and we will return in 30 minutes!". I suposed that in the worst case, the most long that these messages would travel a long distance in up to 10s or a little more, maybe 60s;
2- I know the range depends a lot of factors but in the right conditions, with the right link prediction, how I can put in the T-Beam the right config, offset the app and CLI, and forces the T-Beam to work with my lab config, I mean, I have some parameters that I want to put in radio and prove it's capacity, it is my academical work based on this platform;
3- the data is in semtech SX1261/2 datasheet, that in some tables in its initial pages presents the following parameters that I want to test:
- 10.4 KHz, SF12 to obtain a -148 dBm in pages 18 of 107 in table 3-7 at lines 10 and 11 (BR_L and BW_L), in these cases shows the possibility of a 7.8 KHz BW transmission with a SF=12;
- 19 of 107 in table 3-8 at RXS_LB information that shows the "BW_L = 10.4 kHz, SF = 12" that results in a boosted gain at -148 dBm, and
- page 17 of 107 in table 3-6, shows about the power consumption in transmission mode, that for the SX1262 microcontroller is up to 22 dBm.
4- So, what or with how resources I can explore the maximum potential of this radio? I have four and I want to purchase one more and my intention is put in them the following setup:
10.4 KHz, number of hops = 2 or 3, SF=12, coding rate 4/8 (i need to understand it more, but I realized that this value makes the link more resilient and it sounds like very good), 22 dBm of power, because the links are over than 18 Km, one of them is in 45 Km and one or two are about  3 Km only, but, in general I will need use the full power including to overcome reliefs, vegetation and buildings and even the local electromagnetic spectrum.
5- I will use initially a 2 dBi Omni antenna, original from Lilygo purchased kit and in soon, a 5 dBi Omni antenna, It will be an adventure but is necessary to aproves by an academical work the capacity and eficiency and field application possibilities.
6- I guess you may help me so much in this mission and if meshtastic does not serve or support such a configuration, if you can present me with other options capable of taking advantage of such potential and how to use them on the equipment.
7- I am using the following version of meshtastic firmware, 2.3.6.7a3570a Beta (Stable), I am counting on you and I will do feedbacks about this work.
[DataSheet_SX1261-2_V1.1.pdf](https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/files/15478282/DataSheet_SX1261-2_V1.1.pdf)

**Comment by lewisxhe** [comment]
You should ask questions on the [forum](https://meshtastic.discourse.group/)
