### ISSUE TITLE
How can I insert distinct LoRa config for each channel desired?

### ISSUE THREAD

**Issue by dms-rj** [Xinyuan-LilyGO/LilyGo-LoRa-Series#169]
Hi there!
My doubts is in use of CLI and the tests That I am doing, so I have much doubts and I really hope that you can help me with them:
1- Refer to a title question in follow:
-> Primary Channel: It is necessary that this channel be LongFast ? (I want It as "personal" in three types, 11KHz SF12  Coding Rate as 8, 31Khz as the minimum explained in the meshtastic.org SF12 CR 8, VeryLong_Slow the same as in the meshtastic site); This channel ciphered at base64; GPS as personable in CLI at a value 26 with an almost High Precision;
-> Secondary Channel: as the Primary, but with a Standard PSK, GPS as personable in CLI;
2- Channel 1 named "Wide Area 1", with 11KHz SF12  Coding Rate as 8 and GPS (? I need understand if all channels send GPS info or only the primary, how it works);
3- Channel 2 named "Wide Area 2", with 31KHz SF12  Coding Rate as 8 and GPS (?);
4- Channel 3 named "Wide Area 3", with 62 KHz SF12  Coding Rate as 8 and GPS (?);
5- Channel 4 named "Wide Area 4", with VeryLong_Slow and GPS (?);
6- Channel 5 named "admin", with 11 KHz SF12 CR 8;
7- What means DELIVERED, a cloud with a check in it and RECEIVED that is a person with a check, a technical and an informal explanation about it.
-> Today I was in a test that the radios was an 18.5Km of distance at each other in highest locals positions I have achieved, and the lora config was BW 31 Khz, 2 dBi original antenna Of T Beam SX1262 radio (all of four radios that I have), SF12, and CR 8.
I Hope you all can give the best CLI solution for my case, I want to prove that LORA can communicate even in adverse conditions such as high urban noise, natural and artificial barriers in the middle of the way and even with the original antennas, I will purchase new ones with higher dBi for the same tests, but I don't have them in this exact moment.
8- The position about Rad03 is more difficult to obtain due to bureaucratic reasons. But the solutions that are presented will be very welcome.
In short, I will need a LoRa configuration for each channel. If I put it on channel 2 I want it to send according to the LoRa settings of this channel, if it is on 3 the LoRa settings of 3 and so on.
Example, Channel 2 - LongFast, Channel 3 LongModerate, Channel 4 VeryLong_Slow, Channel 5 BW 11KHz, SF 12, CR 8, PSK, HOP 2 etc.
9- I Didn't informed, the configuration that I used was no good for sending message in movement, I was in car and the radio on top of it, I guess the SF12 and CR 8 was the trouble, because in a fixed position, the packets was sent and I received the "DELIVERED" return at least.

![3](https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/assets/170731694/2dd11ba2-9117-49e1-b666-e207b9c2d544)
![4](https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/assets/170731694/8608d83b-69a4-4713-b311-fc4974d66c73)
![DELIVERED](https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/assets/170731694/c4a41252-d299-4568-87c9-ad8df490f565)
![RECEIVED](https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/assets/170731694/2f7afddb-8468-4664-9609-84676a58f7e6)
![Radio Config LoRa](https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/assets/170731694/da8f6f22-5a74-4400-9d90-7e70fd284e29)
![Lora Mesh Rad01 and Rad02](https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/assets/170731694/18a17bde-9e7f-41d5-b14b-45710f52dfec)
![Lora Mesh Rad01 and Rad04](https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/assets/170731694/e7cea347-3cf8-49e7-8a15-e67716dd82db)
![Lora Mesh Rad03 and Rad02](https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/assets/170731694/291d5144-d180-4eab-86d6-3824a526114e)
![Lora Mesh Rad03 and Rad04](https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/assets/170731694/439266e9-22eb-4b89-81bc-855c66eadf31)
![Radio Config LoRa](https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/assets/170731694/27284fd0-769a-4c9b-a66f-1a01071eb639)

**Comment by lewisxhe** [comment]
You should ask questions on the [forum](https://meshtastic.discourse.group/)
