### ISSUE TITLE
Device stops working and hot after usb plugged in

### ISSUE THREAD

**Issue by fagci** [Xinyuan-LilyGO/LilyGo-LoRa-Series#174]
This component too hot.
Battery was plugged in, but switched off.

![IMG_20240612_162934_244](https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/assets/8795970/bddafcaa-9393-4842-9025-0e48ff413baa)

What it can be and what can I do?

// P.S.: gray wire is single tone buzzer, black wires is two buttons. All works fine earlier. Case was enclosed, environment was room. All wires are insulated with thermo tubes and isolation stripe between board and speaker. Buttons filled w/glue inside separated place of case.

// P.S.2: usb comes from my notebook, works good earlier too...

**Comment by fagci** [comment]
Hm, it boots now after power on with reset pressed and repowered O_o

**Comment by lewisxhe** [comment]
Solve it?

**Comment by fagci** [comment]
Yup, IDK, why this happens, but now its ok. I leave this opened just to information

**Comment by thatSFguy** [comment]
I'm having the same issue.  I have several of these devices, but I'm only having the problem on one.  I'm running Meshtastic. Just to make sure this was not firmware related, I upgraded with a full erase, yet the problem continues.  The node appears to work fine, just gets really hot.
