### ISSUE TITLE
T3S3: Add support to Adruino-esp32

### ISSUE THREAD

**Issue by joyel24** [Xinyuan-LilyGO/LilyGo-LoRa-Series#179]
Please add T3S3 to the supported boards for Arduino-esp32.
I've open an issue here: https://github.com/espressif/arduino-esp32/issues/9927

**Comment by lewisxhe** [comment]
T3-S3 has many variants. A single version is only suitable for one variant and cannot be compatible with all. Using ESP32S3 Dev Module can be more flexible.

**Comment by joyel24** [comment]
> T3-S3 has many variants. A single version is only suitable for one variant and cannot be compatible with all. Using ESP32S3 Dev Module can be more flexible.

I'm not really alright with this answer. For example T-Beam has also many variants but is available in the esp32-arduino boards list with all variants...

<img width="500" alt="Capture d’écran 2024-06-28 à 04 33 36" src="https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/assets/21010316/eed768d3-5412-449f-a7c9-f79a68ce8f21">

**Comment by lewisxhe** [comment]
Ok, you found it, 🤣, I'll find time to update T3

**Comment by lyusupov** [comment]
@joyel24  

https://github.com/espressif/arduino-esp32/pull/9956

<img width="279" alt="image" src="https://github.com/nakhonthai/ESP32APRS_T-TWR/assets/5849637/236c0f78-faff-4d77-9ba4-8f1b1de94710">

**Comment by joyel24** [comment]
https://github.com/espressif/arduino-esp32/issues/9927#issuecomment-2207040234

**Comment by lyusupov** [comment]
@joyel24 
> ... I wanted to wait for the next release ...  before closing the issue...

<img width="856" alt="image" src="https://github.com/user-attachments/assets/5cd31c41-e041-4395-abf9-7afdaec15a33">
