### ISSUE TITLE
LoRa32 V2.1_1.6

### ISSUE THREAD

**Issue by pbh8075** [Xinyuan-LilyGO/LilyGo-LoRa-Series#180]
In the pin diagram, number 27 of mosi, number 5 of sclk, and number 18 of cs are missing. We are suffering because we cannot resolve this. please help
![캡처](https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/assets/173935454/110f9ba0-143f-4c24-b550-90bcf746ad4a)

**Comment by lewisxhe** [comment]
SPI is not reserved on both sides of the board

**Comment by agieocean** [comment]
> SPI is not reserved on both sides of the board

Does this mean you'd need to disable the screen to use the micro sd? Or can you not use the micro sd and the antenna at the same time at all?

Im trying to use the micro sd slot and have not been able to find the proper pin diagram for this board.
