### ISSUE TITLE
T3S3 - Board fails to start with PSRAM set to QSPI

### ISSUE THREAD

**Issue by pksimeonov** [Xinyuan-LilyGO/LilyGo-LoRa-Series#184]
I've been trying out the demos at https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/blob/master/README.MD on a Lilygo T3 S3 v1.2 SX1276 board. The instructions say to set the PSRAM in Arduino IDE's board settings to `QSPI PSRAM`. However, whenever I do that, the upload is fine but the the board fails to start and I get the following on a loop in the Monitor:

```
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0xc (RTC_SW_CPU_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
Saved PC:0x40377d0d
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3818,len:0x508
load:0x403c9700,len:0x4
load:0x403c9704,len:0xad0
load:0x403cc700,len:0x29e4
entry 0x403c9880
E (655) mmap: esp_mmu_unmap(595): munmap target pointer is outside external memory regions

assert failed: spi_flash_munmap flash_mmap.c:241 (0 && "invalid handle, or handle already unmapped")

Backtrace: 0x403776fa:0x3fcf3eb0 0x4037dcad:0x3fcf3ed0 0x40383bbd:0x3fcf3ef0 0x42016373:0x3fcf4020 0x42015ea5:0x3fcf4040 0x42015fa9:0x3fcf4060 0x42016247:0x3fcf4090 0x4200d42f:0x3fcf40f0 0x4200f9a2:0x3fcf4120 0x420a81dd:0x3fcf4150 0x40380a16:0x3fcf4190

ELF file SHA256: 16947e1ec0d78600
```

If I set the PSRAM to `Disabled` and reupload, the board boots fine and the examples are rendered as expected. I managed to reproduce this multiple times. I tried both the OLED SD1366 "UI" and "Simple" example. I have the IDE set to the "ESP32S3 Dev Module" with the settings described in the above readme and I uncommented my board from the `utilities.h` file as instructed, no other modifications to the tested example projects.

Am I doing something wrong or is the "QSPI" setting not valid?

PS Did a test with PSRAM set to "OPI" and it booted up fine.

**Comment by lyusupov** [comment]
@pksimeonov 

<img width="279" alt="image" src="https://github.com/nakhonthai/ESP32APRS_T-TWR/assets/5849637/236c0f78-faff-4d77-9ba4-8f1b1de94710">
