### ISSUE TITLE
Does SX1262 have different sensitivity at different frequencies?

### ISSUE THREAD

**Issue by XieyangSun** [Xinyuan-LilyGO/LilyGo-LoRa-Series#185]
I bought two LoRa nodes from Lilygo, the SX1262-433MHz and SX1262-915MHz. In my actual tests, at all BW&SF combinations (I tested SF6 to SF12, BW from 125kHz to 500kHz), the actual communication distance of the 915MHz node is always farther than that of the 433MHz node when the power is 20dBm.

I am curious why the communication distance of 915MHz is greater than that of 433MHz? In my knowledge, low-frequency signals should have better resistance to attenuation.

I speculate that the difference in sensitivity is caused by the different calculations of the SX1262 chip for 433MHz and 915MHz signals. However, I did not find any description of frequency and sensitivity on the Semtech official website, or any description of how the SX1262 handles different frequency bands.

Does anyone know this detail? I'd really appreciate anyone who can explain this ~

**Comment by lyusupov** [comment]
https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/blob/master/schematic/T-SX1262.pdf
