### ISSUE TITLE
RSSI signal not good

### ISSUE THREAD

**Issue by cmussoni** [Xinyuan-LilyGO/LilyGo-LoRa-Series#187]
![IMG20240704071654](https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/assets/10685435/e8388bfa-7d10-43d5-a23d-758fcdbdd4a9)
Good morning,
I have two "T3 V1.6.1" boards (ESP32 433/868/915MHZ 0.96 Inch OLED SD Card WIFI Module[Q134]), and used the ArduinoLoRa Transmitter and Receiver examples. But the signal, even if the two Esp32 are close, is very bad, it remains between -66 and -70. What could it be? Thanks for a possible answer.
Claudio

**Comment by lewisxhe** [comment]
Try RadioLib, ArduinoLoRa is the default parameter, it does not set the maximum power
https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/tree/master/examples/RadioLibExamples

**Comment by cmussoni** [comment]
> Try RadioLib, ArduinoLoRa is the default parameter, it does not set the maximum power https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/tree/master/examples/RadioLibExamples

Perfect, now I have an RSSI signal between -5 and -8 dBm.
Thanks
Claudio
