### ISSUE TITLE
Updated pin layout image

### ISSUE THREAD

**Issue by icepick3000** [Xinyuan-LilyGO/LilyGo-LoRa-Series#188]
On the LilyGo website it shows this image;

https://cdn.shopifycdn.net/s/files/1/0617/7190/7253/files/pin-diagram_1024x1024.jpg?v=1656990080

However I have the V1.2 version with a different AXP chip but the diagram is for the V1.1 Are the pins still the same on this 1.2 board? The AXP chip is a different one (AXP2101). 
So can someone post an updated schematic?

**Comment by lewisxhe** [comment]
https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/blob/master/schematic/LilyGo_TBeam_V1.2.pdf
