### ISSUE TITLE
Can the T3-S3 be used at 923MHz?

### ISSUE THREAD

**Issue by gilchi** [Xinyuan-LilyGO/LilyGo-LoRa-Series#196]
Can the T3-S3(SX1276 915MHz[H599]) be used at 923MHz?
Is it possible to apply this frequency through software using the LoRa.begin(923E6) function in the LoRa.h library?

**Comment by lewisxhe** [comment]
Of course

**Comment by gilchi** [comment]
"Thank you for your response. So, no special firmware update is needed to use the 923MHz frequency band, right? Also, is there any hardware difference between the SX1276 868MHz [H596] and the SX1276 915MHz [H599]?"

**Comment by lewisxhe** [comment]
The antennas have different frequencies, but the modules are the same
