### ISSUE TITLE
How to minimize energy consumption in sleep mode for a periodic on/off cycle?

### ISSUE THREAD

**Issue by martin229101** [Xinyuan-LilyGO/LilyGo-LoRa-Series#198]
I'm working on a project where I need to minimize the energy consumption of my ESP32 while it's in sleep mode. My goal is to have the device operate for a certain amount of time, then enter sleep mode for one hour, and wake up again after that period.

I have reviewed the deep sleep example, but I'm struggling to fully understand how it works. Specifically, I'm unsure how to implement a reliable cycle where the device sleeps for exactly one hour before waking up and resuming operation.

Here are my specific questions:

What is the best approach to ensure the device sleeps for one hour with minimal energy consumption?
How do I set up the deep sleep mode correctly for this periodic on/off cycle?
Are there any additional tips or best practices to further reduce power consumption in this scenario?
Thank you for your help!

**Comment by lewisxhe** [comment]
It can't be accurate, only about an hour
See here
https://github.com/espressif/arduino-esp32/blob/master/libraries/ESP32/examples/DeepSleep/TimerWakeUp/TimerWakeUp.ino
