### ISSUE TITLE
TTGO V2.1 Custom pogram

### ISSUE THREAD

**Issue by Edgineer10** [Xinyuan-LilyGO/LilyGo-LoRa-Series#200]
Can you upload your own project code to Lilygo TTGO V2.1_1.6 Lora 32 which has paxcounter/ disaster radio default firmware?

**Comment by lewisxhe** [comment]
What's your own code?

**Comment by Edgineer10** [comment]
just the normal send and receive code:
https://github.com/LilyGO/TTGO-LoRa32-V2.1/blob/master/OLED_LoRa_Sender/OLED_LoRa_Sender.ino

**Comment by lewisxhe** [comment]
Oh! Of course you can
