### ISSUE TITLE
GPS Mode for T-Beams module: Continuous?

### ISSUE THREAD

**Issue by richonguzman** [Xinyuan-LilyGO/LilyGo-LoRa-Series#202]
Hi,

Neo6Mv2 GPS modules accept a few configurations modes, but are they selected as a Factory Mode for Lilygo Brand, or are they as Continuous Mode only (the default)??

**Comment by lewisxhe** [comment]
Keep the Ublox factory state, the Lilygo factory test firmware does not configure any module

**Comment by richonguzman** [comment]
thanks for the info ;)
