### ISSUE TITLE
Unused pin for additional sensor

### ISSUE THREAD

**Issue by pongohost** [Xinyuan-LilyGO/LilyGo-LoRa-Series#203]
Hello,

I want to add rotary encoder/other sensor to lilygo lora V2.1_1.6.1. is that possible? are there any unused pins that can be used?

I am already try each pin but no luck. Want to make sure there is unused pin or not.

Thank you

**Comment by lewisxhe** [comment]
Basically all of them are used. Also, VP (36) can only input, vn (39) can only input, GPIO4 (input and output), if you are not using LED lights, then 25 can also be used
![image](https://github.com/user-attachments/assets/16632cf6-a0c9-488f-b6ae-8696aa6c6177)

**Comment by pongohost** [comment]
How about if i don't use SDcard, could i use pin 15,2,14,13?

**Comment by lewisxhe** [comment]
Sure
