### ISSUE TITLE
Can't make LoRa32 T3S3 even boot on Platformio

### ISSUE THREAD

**Issue by richonguzman** [Xinyuan-LilyGO/LilyGo-LoRa-Series#204]
hi,

been struggling with even starting with Lora32 T3S3 V1.2 and print "hello world"

I get into boot loop with core dump:
`E (111) esp_core_dump_flash: Core dump flash config is corrupted! CRC=0x7bd5c66f instead of 0x0
Rebooting...
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0xc (RTC_SW_CPU_RST),boot:0x2a (SPI_FAST_FLASH_BOOT)
Saved PC:0x40377388
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x4bc
load:0x403c9700,len:0xbd8
load:0x403cc700,len:0x2a0c
entry 0x403c98d0
E (80) spi_flash: Detected size(4096k) smaller than the size in the binary image header(8192k). Probe failed.

assert failed: do_core_init startup.c:328 (flash_ret == ESP_OK)`

so I tried with this:
`[env:esp32-s3-devkitm-1]
platform = espressif32 @ 6.7.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_upload.flash_size  = 4MB
board_upload.maximum_size = 4194304
build_flags =
    -DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1`
	
which solved some messages but keep on rebooting... any help to start with it?

**Comment by lewisxhe** [comment]
The default partition table of esp32-s3-devkitc-1 is 8M.
You need to use a 4M partition table. Add in platform.ini

board_build.partitions = default.csv
