### ISSUE TITLE
T-Beam_V1.2 Schematic Circuit

### ISSUE THREAD

**Issue by ajg555** [Xinyuan-LilyGO/LilyGo-LoRa-Series#206]
The schematic for the T-Beam_V1.2 has "T-Beam_V1.1" written on the sheet. Does this version also apply to the "1.2"? I have a question about whether the +5V pin can also charge the batteries, but looking at the current version of the repository, it seems like it can't, since the VSYS (+5V) and the VBUS (5V USB) are on different pins of the AXP2101. However, on my T-Beam_V1.2 module, I noticed that the +5V and the USB VBUS seem to be physically connected, which made me question the source of the schematic. Can you help me with this?

**Comment by lewisxhe** [comment]
Already added. The last one is the 5V pin connected to the USB
