### ISSUE TITLE
Schematic of T3 S3 LR1121?

### ISSUE THREAD

**Issue by matthias-bs** [Xinyuan-LilyGO/LilyGo-LoRa-Series#213]
Hi,

Where can I find the schematic of this board?
https://lilygo.cc/products/t3-s3-lr1121

**Comment by lewisxhe** [comment]
https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/blob/master/schematic/T3_S3_V1.2.pdf
![image](https://github.com/user-attachments/assets/d5a0dcca-4ce1-4728-a08b-cbe40d059b8b)

![image](https://github.com/user-attachments/assets/d611bc21-eb1e-4e2d-8570-1406a1c5ecf9)

**Comment by matthias-bs** [comment]
Thanks for the quick and helpful response. If you are planning an update, a translation of the Chinese text would be helpful.
