### ISSUE TITLE
How to turn the power off when there is a 18650 battery installed?

### ISSUE THREAD

**Issue by HouzuoGuo** [Xinyuan-LilyGO/LilyGo-LoRa-Series#57]
Hello, I have a simple generic sketch running on the TTGo T-Beam (board revision v1.1, 20191212). The sketch displays an image on OLED and that's about it.

When T-Beam is only powered by USB, I can turn the board off by pressing the power button for ~6.5 seconds. However, this does not turn the board off when the board is only powered by a 18650 cell.

So how does the power button work when there's a battery installed?

**Comment by lewisxhe** [comment]
For AXP192, press and hold the PWR button for 6 seconds to turn off the power
