### ISSUE TITLE
A fatal error occurred: Failed to connect to ESP32: Timed out waiting for packet header

### ISSUE THREAD

**Issue by adyb76** [Xinyuan-LilyGO/LilyGo-LoRa-Series#63]
Hi,
I am getting the above error since reloading the software onto my t-beam. I have managed to load compiled code onto this device before, so I am pretty sure the board itself is good. I have also tried a variety of USB cables, and they all produce the same results. I have also tried uploading a test program from the Arduino IDE kit, which also refuses to connect to the t-beam. What can be done about this?

Thanks,
Ade

**Comment by fabiano182** [comment]
I'm going through the same problem. Did you found any solution? Thanks

**Comment by lewisxhe** [comment]
When t-beam fails to download automatically, the fix is
1. Connect to USB,
2. Short IO0 to GND, then keep it connected
3. Press the reset button
4. Upload the program, wait for the upload to complete and remove the short wire

If there are still problems, please reopen
