### ISSUE TITLE
Please provide measurements

### ISSUE THREAD

**Issue by bzed** [Xinyuan-LilyGO/LilyGo-LoRa-Series#70]
Hi,

please provide measurements for your modules, I'm especially interested in the distance and locations of the pin headers on the T-Beam modules. Having to carry around various modules and proper measurement tools is a bit unfortunate when you want to work on projects in your holidays.

Thanks,
Bernd

**Comment by liangyingy** [comment]
Is this what you want?

![image](https://user-images.githubusercontent.com/46518962/182804408-ab946b33-7d29-485c-9abe-6f16bdc39a14.png)

**Comment by bzed** [comment]
@liangyingy This image is mising the distace between the green pin headers columns unfortunately. 
![182804408-ab946b33-7d29-485c-9abe-6f16bdc39a14](https://user-images.githubusercontent.com/119820/182809482-c09eff5f-a4ce-448e-8551-a818ceac46c1.png)

**Comment by bzed** [comment]
(Also the exact location of the pins on the board would be nice, to be able to create an extension baord that with the same screw holes)

**Comment by liangyingy** [comment]
![I6BOTQCDJI )9 THNQ)JYOC](https://user-images.githubusercontent.com/46518962/182818791-cb239a1f-93ad-4757-9d0e-716b34125da7.png)

please get it through cad file.  [t-beam_v1.0](../blob/master/cad/t-beam_v1.0.dwg)

**Comment by bzed** [comment]
@liangyingy Thank you very much!!
