### ISSUE TITLE
Schematic connection

### ISSUE THREAD

**Issue by teegwende** [Xinyuan-LilyGO/LilyGo-LoRa-Series#81]
Hello guys, 
I would like to know better about a product. It's LILYGO® TTGO T-Higrow LoRa Shield 868Mhz Function Expansion Board. The link of the product is : http://www.lilygo.cn/prod_view.aspx?TypeId=50060&Id=1309&FId=t3:50060:3.

I would like to know how to connect this module to arduino Uno, arduino pro mini and raspberry pi 3. 

Thank you

**Comment by lewisxhe** [comment]
T-Higrow exports the SPI interface. If raspberry pie is used, just connect the SPI to raspberry pie

**Comment by teegwende** [comment]
OK thanks for your response. It is not totally clear for me. I was expecting an example of pin connection. But I will give a try again. 

Best regards
