### ISSUE TITLE
PCF8563_SimpleTime.ino cant write time to device

### ISSUE THREAD

**Issue by irqisequalto** [Xinyuan-LilyGO/LilyGo-LoRa-Series#82]
running any of the example codes, the time will not set on the PCF8563 device. and reading it spits out noise like:

 Year :2055 Month:0 Day :0 Hour:14 Minute:74 Sec :0
 Year :1955 Month:0 Day :0 Hour:12 Minute:57 Sec :0
 Year :1952 Month:0 Day :0 Hour:16 Minute:40 Sec :0
 Year :1955 Month:0 Day :0 Hour:20 Minute:29 Sec :0
 Year :1952 Month:0 Day :0 Hour:24 Minute:12 Sec :0
 Year :2054 Month:0 Day :0 Hour:21 Minute:81 Sec :0

I have tried this on 2 of the T-Beam-v1.1 devices

**Comment by lewisxhe** [comment]
https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/blob/master/README.MD#L113-L113

Just only support s3Version

**Comment by irqisequalto** [comment]
So I am unable to access the rtc on the TBeamV1.1 because it's an esp32 device? Is there a rtc on this TBeamV1.1?

**Comment by lewisxhe** [comment]
You cannot use this device. There is no RTC on 1.1

**Comment by irqisequalto** [comment]
That would be why I can't write to it.. thanks!
