### ISSUE TITLE
Reflashing 

### ISSUE THREAD

**Issue by SAN-G-8055** [Xinyuan-LilyGO/LilyGo-LoRa-Series#84]
Initially, I flashed my LILYGO 433/470 w/o LED with micropython, but it was unable to detect GPS. So in order to revert it back I flashed it with `"NMEA_Reset "`.
But now when I am trying to access it with Arduino IDE, there isn't any option for `"TTGO T-Beam"`. There are options of `T-Beam` and `TTGO T1 ` and both of them are showing error 
"The system cannot find the path specified.
exit status 1
Error compiling for board ....".
How to fix this, and what device should I choose next?

**Comment by lewisxhe** [comment]
This is due to incorrect configuration of the installation environment. Please reinstall esp32 arduino
https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html
