### ISSUE TITLE
Supreme is spelled Superme on images and in the documentation

### ISSUE THREAD

**Issue by garthvh** [Xinyuan-LilyGO/LilyGo-LoRa-Series#88]

**Comment by lewisxhe** [comment]
Thank you, the modifications have been completed

**Comment by lyusupov** [comment]
Lewis,
it looks like the schematic link is broken after the last update:

![image](https://user-images.githubusercontent.com/5849637/229702434-5690f1f5-447c-4bb6-801c-381409427cf2.png)

**Comment by lewisxhe** [comment]
Linar.
I saw your commit message after updating the file name and I rename it to match yours, so I ignored the README, it's fixed now

https://github.com/lyusupov/SoftRF/wiki/Prime-Edition-MkIII/_compare/82b095d%5E...82b095d

**Comment by lyusupov** [comment]
Thank you!
